/**
 * Static baseline data object for Demo Account Mode.
 * Unexposes real backend database and APIs by serving completely isolated,
 * realistic baseline data locally in the client.
 */

export const DEMO_BASELINE_DATA = {
  products: [
    {
      id: "prod-demo-1",
      tenantId: "demo-tenant-id",
      name: "Brushless Motor 24V High-Torque",
      sku: "MTR-BRSH-024",
      category: "Machinery",
      unitPrice: 185.0,
      unit_price: 185.0,
      quantity: 42,
      current_stock: 42,
      reorderPoint: 15,
      min_stock_threshold: 15,
      description: "Industrial grade 24V brushless motor for conveyor assemblies",
      createdAt: "2026-09-17T05:34:01.284Z",
      updatedAt: "2026-09-27T05:34:01.284Z",
    },
    {
      id: "prod-demo-2",
      tenantId: "demo-tenant-id",
      name: "Lithium Polymer Pack 48V 20Ah",
      sku: "BAT-LIPO-4820",
      category: "Batteries",
      unitPrice: 320.0,
      unit_price: 320.0,
      quantity: 6,
      current_stock: 6,
      reorderPoint: 10,
      min_stock_threshold: 10,
      description: "High-density energy storage pack with thermal safeguard",
      createdAt: "2026-09-19T05:34:01.284Z",
      updatedAt: "2026-09-27T05:34:01.284Z",
    },
    {
      id: "prod-demo-3",
      tenantId: "demo-tenant-id",
      name: "Optoelectronic Sensor 5V",
      sku: "SEN-OPTO-005",
      category: "Electronics",
      unitPrice: 24.5,
      unit_price: 24.5,
      quantity: 110,
      current_stock: 110,
      reorderPoint: 25,
      min_stock_threshold: 25,
      description: "Precision photoelectric proximity beam sensor",
      createdAt: "2026-09-22T05:34:01.284Z",
      updatedAt: "2026-09-27T05:34:01.284Z",
    },
    {
      id: "prod-demo-4",
      tenantId: "demo-tenant-id",
      name: "Titanium Hex Bolts M8x40 (Box 50)",
      sku: "FST-TI-M840",
      category: "Fasteners",
      unitPrice: 48.0,
      unit_price: 48.0,
      quantity: 0,
      current_stock: 0,
      reorderPoint: 12,
      min_stock_threshold: 12,
      description: "Aerospace grade grade-5 titanium corrosion-resistant fasteners",
      createdAt: "2026-09-23T05:34:01.284Z",
      updatedAt: "2026-09-27T05:34:01.284Z",
    },
    {
      id: "prod-demo-5",
      tenantId: "demo-tenant-id",
      name: "Carbon Fiber Plate 500x500mm",
      sku: "MAT-CF-5050",
      category: "Raw Materials",
      unitPrice: 135.0,
      unit_price: 135.0,
      quantity: 18,
      current_stock: 18,
      reorderPoint: 8,
      min_stock_threshold: 8,
      description: "High tensile 3K weave structural plate",
      createdAt: "2026-09-25T05:34:01.284Z",
      updatedAt: "2026-09-27T05:34:01.284Z",
    },
  ],

  customers: [
    {
      id: "cust-demo-1",
      accountNo: "CUST-1001",
      tenantId: "demo-tenant-id",
      name: "Apex Heavy Industries",
      email: "procurement@apexheavy.com",
      phone: "+1 (555) 609-3382",
      company: "Apex Heavy Industries",
      industry: "Heavy Machinery",
      totalSpend: 210000,
      status: "ACTIVE",
      createdAt: "2026-09-15T05:34:01.284Z",
    },
    {
      id: "cust-demo-2",
      accountNo: "CUST-1002",
      tenantId: "demo-tenant-id",
      name: "Vanguard Marine Systems",
      email: "supplies@vanguard-marine.com",
      phone: "+1 (555) 881-4412",
      company: "Vanguard Marine Systems",
      industry: "Maritime Logistics",
      totalSpend: 74500,
      status: "ACTIVE",
      createdAt: "2026-09-18T05:34:01.284Z",
    },
    {
      id: "cust-demo-3",
      accountNo: "CUST-1003",
      tenantId: "demo-tenant-id",
      name: "Nexus Robotics Corp",
      email: "elena.r@nexusrobotics.io",
      phone: "+1 (555) 019-2834",
      company: "Nexus Robotics Corp",
      industry: "Robotics & Automation",
      totalSpend: 112000,
      status: "ACTIVE",
      createdAt: "2026-09-20T05:34:01.284Z",
    },
  ],

  stockLogs: [
    {
      id: "log-demo-1",
      productId: "prod-demo-1",
      productName: "Brushless Motor 24V High-Torque",
      sku: "MTR-BRSH-024",
      changeType: "IN",
      quantityDelta: 20,
      previousQuantity: 22,
      newQuantity: 42,
      reason: "Supplier batch delivery #PO-9812",
      executedBy: "Alex Reynolds (Demo)",
      createdAt: "2026-09-27T00:34:01.284Z",
    },
    {
      id: "log-demo-2",
      productId: "prod-demo-2",
      productName: "Lithium Polymer Pack 48V 20Ah",
      sku: "BAT-LIPO-4820",
      changeType: "OUT",
      quantityDelta: -4,
      previousQuantity: 10,
      newQuantity: 6,
      reason: "Customer order shipment #ORD-5011",
      executedBy: "Alex Reynolds (Demo)",
      createdAt: "2026-09-26T17:34:01.284Z",
    },
  ],

  leads: [
    {
      id: "lead-demo-1",
      tenantId: "demo-tenant-id",
      title: "Global Robotics Fleet Expansion",
      name: "Global Robotics Fleet Expansion",
      companyName: "AeroTech Automations Inc",
      contactName: "Marcus Vance",
      contactEmail: "marcus@aerotech-auto.com",
      contactPhone: "+1 (555) 392-1049",
      value: 145000,
      stage: "Qualified",
      priority: "HIGH",
      notes: "Urgent need for 24V motors and battery packs before Q4 delivery.",
      createdAt: "2026-09-20T05:34:01.284Z",
      updatedAt: "2026-09-27T05:34:01.284Z",
    },
    {
      id: "lead-demo-2",
      tenantId: "demo-tenant-id",
      title: "Autonomous Delivery Drone Supply",
      name: "Autonomous Delivery Drone Supply",
      companyName: "SkyGlide Deliveries",
      contactName: "Elena Rostova",
      contactEmail: "elena@skyglide.io",
      contactPhone: "+1 (555) 778-9901",
      value: 85000,
      stage: "Proposal",
      priority: "HIGH",
      notes: "Proposal submitted for 200 high-density 48V battery units.",
      createdAt: "2026-09-22T05:34:01.284Z",
      updatedAt: "2026-09-27T05:34:01.284Z",
    },
    {
      id: "lead-demo-3",
      tenantId: "demo-tenant-id",
      title: "Solar Inverter Sensor Upgrade",
      name: "Solar Inverter Sensor Upgrade",
      companyName: "HelioVolt Energy Corp",
      contactName: "David Chen",
      contactEmail: "dchen@heliovolt.com",
      contactPhone: "+1 (555) 441-2299",
      value: 38000,
      stage: "Contacted",
      priority: "MEDIUM",
      notes: "Requested technical specification sheet for optoelectronic sensors.",
      createdAt: "2026-09-24T05:34:01.284Z",
      updatedAt: "2026-09-27T05:34:01.284Z",
    },
    {
      id: "lead-demo-4",
      tenantId: "demo-tenant-id",
      title: "Manufacturing Plant Re-Tooling",
      name: "Manufacturing Plant Re-Tooling",
      companyName: "Apex Heavy Industries",
      contactName: "Sarah Jenkins",
      contactEmail: "s.jenkins@apexheavy.com",
      contactPhone: "+1 (555) 609-3382",
      value: 210000,
      stage: "Won",
      priority: "HIGH",
      notes: "Contract signed for annual fastener and motor fulfillment.",
      createdAt: "2026-09-15T05:34:01.284Z",
      updatedAt: "2026-09-27T05:34:01.284Z",
    },
  ],

  tasks: [
    {
      id: "task-demo-1",
      tenantId: "demo-tenant-id",
      title: "Follow up with Marcus Vance on AeroTech quotation",
      dueDate: "2026-09-29",
      priority: "HIGH",
      status: "PENDING",
      createdAt: "2026-09-26T05:34:01.284Z",
    },
    {
      id: "task-demo-2",
      tenantId: "demo-tenant-id",
      title: "Restock PO for Titanium Hex Bolts M8x40",
      dueDate: "2026-09-28",
      priority: "HIGH",
      status: "PENDING",
      createdAt: "2026-09-25T05:34:01.284Z",
    },
    {
      id: "task-demo-3",
      tenantId: "demo-tenant-id",
      title: "Send battery compliance specs to SkyGlide Deliveries",
      dueDate: "2026-10-01",
      priority: "MEDIUM",
      status: "COMPLETED",
      createdAt: "2026-09-23T05:34:01.284Z",
    },
  ],

  charts: [
    {
      id: "chart-demo-1",
      tenantId: "demo-tenant-id",
      title: "Warehouse Stock Valuation by Category",
      chartType: "bar",
      metric: "stock_valuation",
      timeframe: "CURRENT",
      data: [
        { name: "Machinery", value: 7770 },
        { name: "Batteries", value: 1920 },
        { name: "Electronics", value: 2695 },
        { name: "Raw Materials", value: 2430 },
        { name: "Fasteners", value: 0 },
      ],
      createdAt: "2026-09-24T05:34:01.284Z",
    },
    {
      id: "chart-demo-2",
      tenantId: "demo-tenant-id",
      title: "Monthly Order Fulfilment Velocity",
      chartType: "area",
      metric: "order_velocity",
      timeframe: "CURRENT",
      data: [
        { name: "Week 1", value: 12400 },
        { name: "Week 2", value: 14200 },
        { name: "Week 3", value: 18900 },
        { name: "Week 4", value: 24500 },
      ],
      createdAt: "2026-09-25T05:34:01.284Z",
    },
  ],

  notifications: [
    {
      id: "notif-demo-1",
      title: "Critical Stock Warning",
      message: "Titanium Hex Bolts M8x40 reached 0 units. Reorder recommended.",
      type: "ALERT",
      isRead: false,
      createdAt: "2026-09-27T04:30:00.000Z",
    },
    {
      id: "notif-demo-2",
      title: "Deal Pipeline Milestone",
      message: "Apex Heavy Industries deal moved to Won ($210,000).",
      type: "SUCCESS",
      isRead: true,
      createdAt: "2026-09-26T18:00:00.000Z",
    },
  ],

  conversations: [
    {
      id: "conv-demo-1",
      title: "Stock Audit & Reorder Recommendations",
      agentId: "supply-chain-agent",
      createdAt: "2026-09-26T23:34:01.284Z",
      messages: [
        {
          id: "msg-demo-1",
          sender: "USER",
          content: "Can you review our low stock items and give me a summary?",
          createdAt: "2026-09-26T23:34:01.284Z",
        },
        {
          id: "msg-demo-2",
          sender: "AGENT",
          content: "I have analyzed your warehouse inventory: **Titanium Hex Bolts M8x40** is currently **Out of Stock** (0 units vs. 12 reorder threshold). **Lithium Polymer Pack 48V** is also on **Low Stock Alert** with only 6 units remaining (min threshold 10).\n\nWould you like me to draft an autonomous purchase order or restock action for these items?",
          createdAt: "2026-09-26T23:34:03.284Z",
          sources: [
            "Warehouse Inventory Master",
            "Safety Stock Policy v2.4",
          ],
        },
      ],
    },
  ],
};
