[newrelic]
# App name & license key will automatically fall back to env variables:
# NEW_RELIC_APP_NAME and NEW_RELIC_LICENSE_KEY
log_file = stderr
log_level = info
high_security = false
distributed_tracing.enabled = true
attributes.include = request.parameters.*

[application_logging]
enabled = true
forwarding.enabled = true
metrics.enabled = true

[transaction_tracer]
enabled = true
transaction_threshold = apdex_f
record_sql = obfuscated
stack_trace_threshold = 0.5
explain_enabled = true
explain_threshold = 0.5

[error_collector]
enabled = true

[browser_monitoring]
auto_instrument = false

[thread_profiler]
enabled = true